# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://unbornconcepts.com
title: Unborn Concepts
email: nick@unbornconcepts.com
description: We bring your application to life

excerpt_separator: <!--more-->

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/UnbornConcepts
  - title: github
    url: https://github.com/unbornconcepts

collections:
  services:
    
